### ISSUE TITLE
Добавить условия "cases"

### ISSUE THREAD

**Issue by vadimtsabutashvili** [vadimtsabutashvili/prodLang#5]
```
outputs:
  cases:
    - case: default
      output: "Отобразить название пункта назначения в формате 'Адрес, населённый пункт, район, область'"
    - case: "Значение адрес пустое"
      output: "Отобразить название пункта назначения в формате 'Без адреса, населённый пункт, район, область'"
```
